general:
  num_workers: 8
  gpus: [0, 1, 2, 3]
flow:
  flownet2_dir: "/home/dxyang/code/flownet2"
tracker:
  visualize: False
model:
  joint:
    dir: "release/model/joint/"
    step: 4999
  joint_no_ytvos:
    dir: "release/model/joint_no_ytvos"
    step: 1999
  appearance:
    dir: "release/model/appearance/"
    step: 89999
  motion:
    dir: "release/model/motion/"
    step: 9999
